pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                echo 'Here is new java source code'
                sh 'javac Hello.java'
            }
        }
        stage('run') {
            steps {
                echo 'Running new java code.'
                sh 'Hello new java'
            }
        }
    }
}